- CHANGELOG.md
- lib/plek/version.rb
This releases #23, giving us the `find_uri` method.
> Release version 1.10.0

- LICENCE
- README.md
- lib/plek.rb
- plek.gemspec
The updated rdocs won't show up on rubydoc.info until an updated gem is released.  They can be viewed locally by install the `yard` gem, and then running `yard doc` in the root of the project.  You can then open `doc/index.html` in a browser.
> Add API docs, a Licence, and improve the README.

- go/plek.go
- go/plek_test.go
useful in development and test environments and keeps it consistent with Plek.rb.
> In absence of GOVUK_APP_DOMAIN use dev.gov.uk

- go/plek.go
This makes the package level `Find` function consistent with the `Find`
instance method on `Plek`.
> [Go] Rename variable name for consistency.

- go/plek.go
- go/plek_test.go
https://trello.com/c/HfNnOLFJ
this allows us to use just Host part of the URL, re-using the other Plek logic.
hat-tip: @alext
> Return *url.URL from plek.go

- CHANGELOG.md
- go/plek.go
- go/plek_test.go
- lib/plek.rb
- test/plek_test.rb
When `PLEK_HOSTNAME_PREFIX` is set, it will be prepended to the returned host.
This behaviour is overridden by the `PLEK_SERVICE_xxx_URI` functionality, because prepending plus manual override would cause unexpected behaviour.
We intend to use this in the draft stack to append `draft-` to our hostnames.
> Allow an ENV variable to be prepended to the host

- test/plek_test.rb
- test/service_uri_test.rb
- test/uri_test.rb
These were'nt cleaning up properly after themselves, and were therefore
order dependent.
> Fix flakey tests.

- test/website_root_test.rb
Because this was cleaning up in a before, not an after it could
potentially leak environment settings into other tests.
> Fix another test cleanup.

- jenkins.sh
- plek.gemspec
- test/asset_root_test.rb
- test/plek_test.rb
- test/service_uri_test.rb
- test/test_helper.rb
- test/uri_test.rb
- test/website_root_test.rb
We should test this library against the versions of Ruby we use in production. Testing against Ruby 2.2 requires the minitest gem, as minitest is no longer part of stdlib.
Also, stub env variables instead of changing ENV hash. This now uses ClimateControl to stub the environment instead of directly
modifying the ENV hash. This allows the tests to be run in a random order.
> Run tests under multiple rubies

- README.md
Documentation on the environment variables from apps that use Plek (such as [this](https://github.com/alphagov/static#running-locally) from static) don't explain what they do and you currently have to find the [code that uses them](https://github.com/alphagov/plek/blob/master/lib/plek.rb#L159) to understand this.
This adds some explanation to the README.
> Add documentation on Plek environment variables

- lib/plek.rb
- test/asset_root_test.rb
- test/public_asset_host_test.rb
This returns the `GOVUK_ASSET_HOST`, which is suitable for public
consumption. This will resolve to
https://assets.digital.cabinet-office.gov.uk in production.
This is mostly needed for Publishing apps like Whitehall to
differentiate between the Rails-style asset root used to serve JS and
CSS for Admin interfaces, versus the public CDN that they should
reference in content that is pushed to publishing-api.
> Add public_asset_host method

- README.md
- I was just explaining Plek to someone and referred to the README,
only to notice that it still referenced "production.alphagov.co.uk" rather
than "publishing.service.gov.uk" for production hosts. Testing this on
Integration, "Plek.new.find('frontend')" returns
"https://frontend.integration.publishing.service.gov.uk", so I assume it works the
same way in production.
> Use "publishing.service.gov.uk" as the example production hostname

- test/service_uri_test.rb
Add a test to document that if `PLEK_SERVICE_FOO_URI` is set, then the
`force_http` parameter is ignored.
* * *
It feels like this is a bug as `force_http` implies to me that the URI scheme will be set to `http` no matter what. Either way, I think it's helpful to document in the tests. I couldn't see an equivalent in the Go library.
> Add a test to document that force_http ignored

- test/service_uri_test.rb
We started using ClimateControl to set environment variables in
ae30a91aa, but this test was written before that change. This change
also appears to fix a broken build under Ruby 2.2.4:
1) Failure:
PlekTest#test_should_prepend_data_from_the_environment [/home/jenkins/workspace/govuk_plek/test/plek_test.rb:96]:
--- expected
+++ actual
@@ -1 +1 @@
-"https://test-foo.preview.alphagov.co.uk"
+"https://foo.localhost:5001"
https://ci.dev.publishing.service.gov.uk/job/govuk_plek/89/console
> Update test to use ClimateControl

- CHANGELOG.md
- lib/plek.rb
For ruby 2.3 or greater, if there is an explicit URI set for the
service in the environment, the return value is already frozen. For
consistency, always return a frozen string.
> Freeze the strings returned from Plek.find

- CHANGELOG.md
- README.md
- lib/plek.rb
Introducing the need for this environment variable (in https://github.com/alphagov/plek/pull/55) seems to have
caused a variety of pain points with situations where we don't have a
GOVUK_APP_DOMAIN_EXTERNAL set. Frequently we're seeing builds fail due
to the missing env var. In most cases where it doesn't exist
GOVUK_APP_DOMAIN is set to an external domain anyway.
This sets the env var to fallback to the parent domain if that is set
which should make this change now backwards compatible.
> Fallback to GOVUK_APP_DOMAIN when GOVUK_APP_DOMAIN_EXTERNAL isn't set

- lib/plek.rb
This removes the ability to switch to a custom DEV_DOMAIN, with the
assumption that this functionality is never used.
> Remove redundant DEV_DOMAIN env var

- plek.gemspec
This prevents developers using different versions of rubocop depending on when they cloned the repo (as there is no Gemfile.lock committed).
> Set specific version of rubocop-govuk

- Rakefile
We don't care about a clang formatting and can use Rubocop's default rake task.
Motivation for change was routine TLC
> Simplify rubocop configuration

- .github/dependabot.yml
- .github/workflows/ci.yml
- Jenkinsfile
Trello: https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions
Tests and releases will now be managed by GitHub actions. This is in
preparation for GOV.UK's eventual retirement of Jenkins CI.
> Replace Jenkinsfile with GitHub action

- CHANGELOG.md
- README.md
- lib/plek.rb
- test/plek_test.rb
We need some more flexibility in how Plek constructs URLs for services, in order to keep the complexity of govuk-helm-charts within reasonable bounds and keep everything maintainable.
- Support empty domain suffixes. This simplifies GOV.UK's Helm charts by eliminating the need to construct domain names containing the environment name. We can simply use the cluster DNS like we're supposed to, so the hostname for Content Store is just `content-store` and the local resolver expands that to `content-store.apps.svc.cluster.local`. This makes it somewhat easier to retire Plek in the long run.
- Support a list of hostnames to exclude from `PLEK_HOSTNAME_PREFIX`. This simplifies the configuration of the draft stack by saving us from having to specify a bunch of overrides for every draft app.
- …
> Add features needed by Replatforming.

- CHANGELOG.md
- lib/plek.rb
- test/plek_test.rb
This method was put in temporarily 10 years ago [1] and has had a todo next to it ever since. We're planning to finally remove this [2] in the 5.0 release so this acts as a warning in the interim.
[1]: https://github.com/alphagov/plek/commit/309ef5942a7adcdc6d68a9416fa3267c17a2268f
[2]: https://github.com/alphagov/plek/pull/93
> Deprecate the use of Plek.current

- CHANGELOG.md
- Gemfile
- README.md
- lib/plek.rb
- lib/plek/version.rb
- test/plek_test.rb
If we wanted to be super strict, we could view removing the unused setter methods for `parent_domain` and `external_domain` as a compatibility-breaking API change. There isn't a single usage of these anywhere though, so in practice it's more helpful to consider this a minor release as it's supposed to be 100% compatible with all existing usage.
Also, start using `https` when fetching gem dependencies during build.
> Release version 4.1.0.

- CHANGELOG.md
- lib/plek/version.rb
This contains a number of breaking changes so apps should be careful when adopting this.
> Release 5.0.0
